title: Siwakorn Siwaworawet
logo: /assets/img/headshot_circle.png
# The symbol '>' lets us write multiple lines of HTML text below
description: >
  <center>
    <a href="resume.pdf">Resume</a> | 
    <a href="https://www.linkedin.com/in/siwakorn-siwaworawet-92b085384/">LinkedIn</a> | 
    <a href="mailto:siwakorn.siwaworawet@gmail.com">Email</a>
  </center>
  <br>
  Civil Engineering graduate from <strong>KMUTT</strong>. Passionate about applying advanced structural analysis to solve real-world engineering challenges and deliver safe, sustainable infrastructure.
  <br><br>
  <strong>Email:</strong> siwakorn.siwaworawet@gmail.com
  <br><br>
  # Education

  **King Mongkut's University of Technology Thonburi (KMUTT)**
  <br>*B.Eng. in Civil Engineering* | Aug 2022 –  June 2026
  * **Relevant Coursework:** Structural Analysis, Reinforced Concrete Design, Construction Management, Foundation Engineering.

  <hr style="margin: 50px 0;">

show_downloads: false
theme: jekyll-theme-minimal
